[package]
name = "liveatc"
version = "0.1.0"
authors = ["Sequal32 <connor0530@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4"
crossbeam-deque = "0.7"
regex = "1"
reqwest = {version = "0.10.8", features=["blocking"]}
quick-xml = "0.18"
serde_json = "1.0"
serde = {version = "1.0", features=["derive"]}